"""Web assistant: page delivery, Slack-issued sign-in, and the chat API.

The browser only talks to these endpoints; every request is answered by the same
AccountIntelligenceAgent used by Slack, so CRM behavior is identical on both surfaces.
"""

import logging
from datetime import UTC, datetime
from pathlib import Path
from typing import Annotated, Literal

from fastapi import APIRouter, Depends, Request
from fastapi.responses import FileResponse, RedirectResponse, Response
from pydantic import BaseModel, ConfigDict, Field

from app.agent.schemas import AgentRequest, AgentResponse
from app.agent.service import AccountIntelligenceAgent
from app.api.errors import AppError
from app.api.slack import get_action_safety, get_agent
from app.db.session import UnitOfWork
from app.repositories.hubspot_oauth import HubSpotOAuthRepository
from app.services.action_safety import ActionSafetyService, RecentAction
from app.web.session import (
    SESSION_COOKIE,
    SESSION_TTL_SECONDS,
    WebIdentity,
    WebSessionSigner,
)

logger = logging.getLogger(__name__)

WEB_DIR = Path(__file__).resolve().parent.parent / "web"
STATIC_DIR = WEB_DIR / "static"
_INDEX = WEB_DIR / "index.html"

# The page loads only its own assets and talks only to this origin; it never calls HubSpot.
_PAGE_HEADERS = {
    "Content-Security-Policy": (
        "default-src 'self'; script-src 'self'; style-src 'self'; img-src 'self' data:; "
        "connect-src 'self'; base-uri 'none'; form-action 'self'; frame-ancestors 'none'"
    ),
    "Referrer-Policy": "no-referrer",
    "X-Content-Type-Options": "nosniff",
    "Cache-Control": "no-store",
}

page_router = APIRouter(tags=["web-assistant"])
api_router = APIRouter(prefix="/assistant", tags=["web-assistant"])


class AssistantMessage(BaseModel):
    model_config = ConfigDict(extra="forbid")

    message: str = Field(min_length=1, max_length=3000)
    # Generated by the browser per send; makes a re-sent message idempotent.
    client_message_id: str = Field(pattern=r"^[A-Za-z0-9-]{8,64}$")


class AssistantReply(BaseModel):
    status: str
    text: str
    request_id: str
    result: dict[str, str] | None = None
    cards: list[dict[str, str]] = Field(default_factory=list)


Tone = Literal["success", "info", "warning", "error", "pending"]


class RecentItem(BaseModel):
    title: str
    detail: str | None = None
    tone: Tone
    created_at: datetime


class AssistantSession(BaseModel):
    user_id: str
    hubspot_connected: bool
    recent: list[RecentItem]


def get_signer(request: Request) -> WebSessionSigner:
    secret = request.app.state.settings.slack_signing_secret
    if not secret:
        raise AppError("web_assistant_not_configured", "The web assistant is not configured", 503)
    return WebSessionSigner(secret)


def get_web_identity(
    request: Request, signer: Annotated[WebSessionSigner, Depends(get_signer)]
) -> WebIdentity:
    identity = signer.verify(request.cookies.get(SESSION_COOKIE), purpose="session")
    if identity is None:
        raise AppError("unauthenticated", "Open HubSpot AI from Slack to sign in.", 401)
    return identity


async def get_hubspot_connected(
    request: Request, identity: Annotated[WebIdentity, Depends(get_web_identity)]
) -> bool:
    try:
        async with UnitOfWork(request.app.state.session_factory) as unit_of_work:
            if unit_of_work.session is None:
                return False
            token = await HubSpotOAuthRepository(unit_of_work.session).get_token(
                identity.tenant_id
            )
    except Exception:
        logger.warning("HubSpot connection lookup failed", exc_info=True)
        return False
    return token is not None


@page_router.get("/assistant", include_in_schema=False)
async def assistant_page(request: Request, token: str | None = None) -> Response:
    if token is None:
        return FileResponse(_INDEX, media_type="text/html", headers=_PAGE_HEADERS)

    # Exchange a Slack-issued link for a session cookie, then drop the token from the URL.
    secret = request.app.state.settings.slack_signing_secret
    signer = WebSessionSigner(secret) if secret else None
    identity = signer.verify(token, purpose="link") if signer else None
    response = RedirectResponse(
        "/assistant" if identity else "/assistant?link=expired",
        status_code=303,
        headers=_PAGE_HEADERS,
    )
    if signer is not None and identity is not None:
        response.set_cookie(
            SESSION_COOKIE,
            signer.issue(identity, purpose="session", ttl_seconds=SESSION_TTL_SECONDS),
            max_age=SESSION_TTL_SECONDS,
            httponly=True,
            secure=True,
            samesite="lax",
            path="/",
        )
    return response


@api_router.get("/session", response_model=AssistantSession)
async def assistant_session(
    identity: Annotated[WebIdentity, Depends(get_web_identity)],
    connected: Annotated[bool, Depends(get_hubspot_connected)],
    action_safety: Annotated[ActionSafetyService, Depends(get_action_safety)],
) -> AssistantSession:
    try:
        recent = await action_safety.recent_actions(
            tenant_id=identity.tenant_id, actor_id=identity.user_id
        )
    except Exception:
        logger.warning("Recent activity lookup failed", exc_info=True)
        recent = []
    now = datetime.now(UTC)
    return AssistantSession(
        user_id=identity.user_id,
        hubspot_connected=connected,
        recent=[recent_item(action, now) for action in recent],
    )


@api_router.post("/messages", response_model=AssistantReply)
async def assistant_message(
    request: Request,
    body: AssistantMessage,
    identity: Annotated[WebIdentity, Depends(get_web_identity)],
    agent: Annotated[AccountIntelligenceAgent, Depends(get_agent)],
) -> AssistantReply:
    # FastAPI only parses JSON bodies sent as application/json, so form posts from other
    # sites cannot reach this handler.
    request_id = request.state.request_id
    try:
        # Same entry point as Slack: one source of truth for CRM processing.
        response = await agent.respond(
            AgentRequest(
                tenant_id=identity.tenant_id,
                actor_id=identity.user_id,
                message=body.message.strip() or body.message,
                request_id=request_id,
                channel_id=f"web:{identity.user_id}",
                message_ts=body.client_message_id,
            )
        )
    except Exception:
        logger.exception("Web assistant request failed", extra={"tenant_id": identity.tenant_id})
        response = AgentResponse(
            status="unavailable",
            text="Something went wrong while processing your request. Please try again.",
            request_id=request_id,
        )
    return AssistantReply(
        status=response.status,
        text=response.text,
        request_id=response.request_id,
        result=response.result,
        cards=response.cards,
    )


def recent_item(action: RecentAction, now: datetime) -> RecentItem:
    """Plain-language summary of a recorded CRM action for the sidebar."""
    payload = action.payload
    created = action.created_at if action.created_at.tzinfo else action.created_at.replace(
        tzinfo=UTC
    )
    expires = action.expires_at if action.expires_at.tzinfo else action.expires_at.replace(
        tzinfo=UTC
    )

    def item(title: str, detail: str | None, tone: Tone) -> RecentItem:
        return RecentItem(title=title, detail=detail, tone=tone, created_at=created)

    if action.action_type == "crm_plan":
        request_text = str(payload.get("request") or "")
        detail = request_text if len(request_text) <= 60 else request_text[:59] + "…"
        return {
            "completed": item("Request completed", detail, "success"),
            "failed": item("Request not completed", detail, "error"),
            "reconciliation_required": item("Partially completed", detail, "warning"),
        }.get(action.status, item("In progress", detail, "pending"))

    if action.action_type == "create_contact":
        name = " ".join(
            str(payload[key]) for key in ("firstname", "lastname") if payload.get(key)
        ) or str(payload.get("email") or "Contact")
        return {
            "completed": item("Contact created", name, "success"),
            "failed": item("Contact not created", name, "error"),
            "reconciliation_required": item("Needs review", name, "warning"),
        }.get(action.status, item("Creating contact", name, "pending"))

    kind, verb = {
        "update_contact": ("contact", "Update"),
        "delete_contact": ("contact", "Delete"),
        "update_company": ("company", "Update"),
        "update_deal": ("deal", "Update"),
    }.get(action.action_type, ("record", "Change"))
    label = str(
        payload.get(f"{kind}_name") or payload.get(f"{kind}_id") or payload.get("contact_id") or ""
    )
    detail = f"{kind.capitalize()} {label}".strip()
    if action.status == "pending":
        if expires <= now:
            return item(f"{verb} expired", detail, "info")
        return item("Awaiting confirmation", f"{verb} · {detail}", "pending")
    past = {"Update": "Updated", "Delete": "Deleted"}.get(verb, "Changed")
    return {
        "completed": item(f"{kind.capitalize()} {past.lower()}", label or None, "success"),
        "failed": item(f"{verb} failed", detail, "error"),
    }.get(action.status, item(f"{verb} in progress", detail, "pending"))
